<h1 aligen="center"style="color:green"> NumPy Task 1 </h1>

## 1)Create a 1D NumPy array of numbers from 0 to 9.

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2)Create a 2D array of shape (3, 3) with all elements as 1.

In [4]:
arr = np.ones((3, 3))
arr


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 3)Generate a NumPy array of 15 random integers between 10 and 50

In [5]:
arr = np.random.randint(10, 51, 15)
arr


array([19, 20, 26, 15, 21, 36, 16, 29, 50, 34, 16, 23, 46, 44, 33])

In [6]:
arr = np.random.randint(12, 34, 45)
arr

array([30, 22, 29, 25, 29, 28, 28, 29, 32, 20, 27, 14, 31, 26, 19, 15, 20,
       21, 32, 32, 33, 19, 26, 16, 31, 12, 19, 22, 17, 29, 31, 16, 29, 31,
       20, 22, 27, 13, 22, 16, 23, 13, 16, 29, 16])

## 4)Create an array of 5 evenly spaced numbers between 0 and 1 (inclusive).

In [7]:
arr = np.linspace(0, 1, 5)
arr


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 5)Create a 4x4 identity matrix using NumPy.

In [8]:
arr = np.eye(4)
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 6)Create an array from the list [10, 20, 30, 40] and change the data type to float.

In [9]:
arr = np.array([10, 20, 30, 40], dtype=float)
arr


array([10., 20., 30., 40.])

## 7)Create a 3x3 array with values from 1 to 9, then extract the second column.

In [10]:
arr = np.arange(1, 10).reshape(3, 3)
second_col = arr[:, 1]
(second_col)


array([2, 5, 8])

## 8)Create a 1D array with 10 elements and reshape it into a 2x5 matrix.

In [11]:
arr = np.arange(10).reshape(2, 5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 9)Create two 2x2 matrices and perform matrix multiplication.

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
result


array([[19, 22],
       [43, 50]])

## 10)    Given the array arr = np.array([5, 12, 7, 18, 3]), replace all values greater than 10 with 100.



In [14]:
arr = np.array([5, 12, 7, 18, 3])
arr[arr > 10] = 100
arr


array([  5, 100,   7, 100,   3])